### ISSUE TITLE
Embed existing documentation into this project

### ISSUE THREAD

**Issue by nkutsche** [schematron-quickfix/escali-package#9]
Feedback from issue #8:

> Are there any User Guide for add-on? Intuitively I couldn't figured out how to use it. I could only open Options ; other buttons are inactive

First hint: Open a document which is connected to a Schematron Schema (with the PI `<?xml-model ...`). You can add such a PI with Document > Schema > Associate schema...
(_Make sure, the option "Detect schema by processing-instruction <?xml-model?>" in the Escali Plugin Options is active_)

Then you should see the Schematron report in the "Escali Schematron" view.

**Comment by nkutsche** [comment]
Argh! Just found, I have it already:

[Hidden on GitHub](https://github.com/nkutsche/presentations-EscaliOxygenPlugin)

**Comment by OS-50101** [comment]
Hi!
I enabled the Escali in oXygen:

![image](https://user-images.githubusercontent.com/24490898/52337861-1e200d00-2a09-11e9-918b-8039d50b638b.png)

Then validated the document using a validation scenario. It worked as usual, no error messages in Escali Schematron View Pane. 

Then I tried to associate the schematron file with the xml document as you recommended and I get following message:

> Failed to load document file:/C:/.../schemas/integrated-styleguide_DIME/src/rules/library.sch#checkAttributeValue
>  Failed to load document file:/C:/.../schemas/integrated-styleguide_DIME/src/rules/library.sch#checkAttributeValue 

So it looks like a problem with resolving the references as the validation scenario refers to rules.sch (part of the intergrated styleguide project).

Then I associated the file with a standalone schmatron file and I got 11 error-messages :

_System ID: C:\Users\\Documents\dme_repos\branches\repos_develop_os\trunk_branch-os\schemas\integrated-styleguide_DIME\src\rules\schematron-DME.sch
Engine name: Escali Schematron
Severity: fatal
Description: Invalid content was found starting with element '{"http://purl.oclc.org/dsdl/schematron":p}'. One of '{"http://purl.oclc.org/dsdl/schematron":extends, "http://purl.oclc.org/dsdl/schematron":report, "http://purl.oclc.org/dsdl/schematron":include, "http://purl.oclc.org/dsdl/schematron":let, "http://purl.oclc.org/dsdl/schematron":assert, WC[""], WC[##other:"http://purl.oclc.org/dsdl/schematron",""]}' is expected.
Offset: 3_

and one message:

_Validation canceld because of internal error!_

**Comment by nkutsche** [comment]
Hi, I moved that to another issue #10. Please see my comment there.
I added a help page to this project [here](https://github.com/schematron-quickfix/escali-package/blob/master/escaliOxygen/site/README.md).
I close this issue.
